### Create list students request
POST http://localhost:8080/students
Content-Type: application/json

[
  {
    "reference": "STU001",
    "firstName": "Alice",
    "lastName": "Durand",
    "age": 20
  },
  {
    "reference": "STU002",
    "firstName": "Bob",
    "lastName": "Martin",
    "age": 22
  },
  {
    "reference": "STU003",
    "firstName": "Charlie",
    "lastName": "Dupont",
    "age": 19
  }
]

### 